"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = "$all$time$cmd_duration$line_break$battery$status$container$shell$character"
palette = "gruvbox"
continuation_prompt = "â€¦  "

# https://starship.rs/presets/no-nerd-font.html
[battery]
full_symbol = "â€¢ "
charging_symbol = "â‡¡ "
discharging_symbol = "â‡£ "
unknown_symbol = "â“ "
empty_symbol = "â— "

[erlang]
symbol = ""

[pulumi]
symbol = ""

[nodejs]
symbol = "[â¬¡](bold green) "
format = "[via](fg) [$symbol($version )]($style)"

[[battery.display]]
# "bold red" style when capacity is between 0% and 15%
threshold = 15
style = "bold red"

[[battery.display]]
threshold = 25
style = "bold orange"

[[battery.display]]
# don't display batter when the capacity is above this threshold
threshold = 35
style = "bold yellow"

[character]
success_symbol = "[â±](bold green-light) "
error_symbol = "[âœ˜](bold red-light) "

[cmd_duration]
format = "[took](fg) [$duration]($style) "
show_notifications = false
min_time = 3000
style = "bold yellow"

[directory]
style = "bold aqua"
truncation_length = 0

[hg_branch]
symbol = "ï„¦"

[git_branch]
format = "[on](fg) [$symbol $branch(:$remote_branch)]($style) "
style = "bold blue"
symbol = "ï„¦"

[git_metrics]
disabled = true

[git_status]
style = "bold blue"
ahead = "[>$count](aqua-light)"
diverged = "[$behind_count<](orange-light)[>$ahead_count](aqua-light)"
behind = "[$count<](orange-light)"
staged = "[+$count](green)"
deleted = "[-$count](red)"
untracked = "[%$count](purple)"
modified = "[*$count](yellow)"
stashed = "[\\$$count](orange)"
renamed = "[~$count](aqua)"
conflicted = "[!$count](red-light)"

[package]
format = "[is](fg) [$symbol $version]($style) "
style = "bold orange"
symbol = "ï†² " # ğŸ™­ î¬©

[sudo]
disabled = false
symbol = "âˆš "
format = "[[as](fg) $symbol]($style)"

[time]
disabled = false
format = "[at](fg) [$time]($style) "
style = "yellow bold"
time_format = "%T"

[username]
format = "[$user]($style) [in](fg) "

[jobs]
disabled = true

# from https://github.com/morhetz/gruvbox
[palettes.gruvbox]
red = "#cc2418"
red-light = "#fb4934"
green = "#98971a"
green-light = "#b8bb26"
yellow = "#d79921"
yellow-light = "#fabd2f"
purple = "#b16286"
purple-light = "#d3869b"
aqua = "#689d6a"
aqua-light = "#8ec07c"
orange = "#d65d0e"
orange-light = "#fe8019"
gray = "#928374"
gray-light = "#a89984"
gray-dark = "#928374"
fg = "#ebdbb2"
fg0 = "#fbf1c7"
fg1 = "#ebdbb2"
fg2 = "#d5c4a1"
fg3 = "#bdae93"
fg4 = "#a89984"
bg = "#282828"
bg0-h = "#1d2021"
bg0-s = "#32302f"
bg0 = "#282828"
bg1 = "#3c3836"
bg2 = "#504945"
bg3 = "#665c54"
bg4 = "#7c6f64"
